### ISSUE TITLE
No se calcula correctamente la raíz de la palabra niñez

### ISSUE THREAD

**Issue by dzapata14** [lopezezequiel/Stemmer_es#1]
Saludos a todos,

Estoy probando esta herramienta que está super genial, sin embargo he detectado que hay términos que no se calculan correctamente, tal es el caso de la palabra niñez, la cual devuelve como raíz a la misma palabra, en cambio, si calculamos la palabra niño si retorna como resultado niñ.

**Comment by lopezezequiel** [comment]
Hola @dzapata14. Gracias por contactarme y perdón por la demora en responder. De acuerdo al algoritmo de Porter el stem de la palabra niño es niñ y de niñez es niñez. Recordar que stem no es lo mismo que lexema aunque generalemente coincidan. Como explico en la entrada de mi blog https://lopezezequiel.com/stemmer_es-js/ el algoritmo de Porter consiste en un conjunto de reglas básicas pensado para hallar el lexema en la mayoría de los casos pero no en todos. La idea es mantener un costo computacional bajo. Recordar que los leguajes naturales están plagados de excepciones y por tanto la única forma de obtener el lexema de una palabra sería tener un diccionario con todas las palabras o al menos todas las excepciones. Para comprobar que ambos stem estan correctos podes verificarlo en el diccionario de pruebas de tartarus http://snowball.tartarus.org/algorithms/spanish/diffs.txt que es el mismo que uso para el test de la librería. Saludos y ante cualquier problema abrime un nuevo issue.
